import type {
  ChecklistCategory,
  Day,
  Person,
  Roadmap,
  Step,
  Vehicle,
} from './types'

export const ROADMAP_VERSION = 1

/** Shoot weekend dates (éditables via l'import JSON). */
const D = {
  fri: '2026-06-26',
  sat: '2026-06-27',
  sun: '2026-06-28',
} as const

const at = (date: string, hm: string) => `${date}T${hm}:00`

interface StepSeed {
  id: string
  title: string
  phase: string
  start: string
  end: string
  location?: string
  participants?: string[]
  equipment?: string[]
  vehicles?: string[]
  details?: string[]
}

function step(seed: StepSeed): Step {
  return {
    id: seed.id,
    title: seed.title,
    phase: seed.phase,
    start: seed.start,
    end: seed.end,
    location: seed.location,
    participants: seed.participants ?? [],
    equipment: seed.equipment ?? [],
    vehicles: seed.vehicles ?? [],
    shots: [],
    details: seed.details ?? [],
    override: 'auto',
    shiftMinutes: 0,
    comments: [],
  }
}

const vendredi: Day = {
  id: 'vendredi',
  label: 'Vendredi',
  date: D.fri,
  subtitle: 'Plateau de Vitrolles — SOUS DROP',
  steps: [
    step({
      id: 'fri-prepa-voiture',
      title: 'PRÉPA — Voiture & Matériel',
      phase: 'Prépa',
      start: at(D.fri, '15:00'),
      end: at(D.fri, '17:00'),
      location: 'Sunset Cam',
      participants: ['Benny'],
      equipment: ['Voiture location', 'Matériel lumière'],
      details: [
        'Récupération voiture location',
        'Retrait matériel lumière Sunset Cam',
        'Vérification matériel',
      ],
    }),
    step({
      id: 'fri-maquillage',
      title: 'MAQUILLAGE / STYLISME',
      phase: 'Maquillage',
      start: at(D.fri, '15:00'),
      end: at(D.fri, '17:00'),
      participants: ['Mad', 'Eva', 'Lea', 'Tehazed'],
    }),
    step({
      id: 'fri-gare',
      title: 'GARE SAINT-CHARLES — Arrivée équipe',
      phase: 'Trajet',
      start: at(D.fri, '16:15'),
      end: at(D.fri, '17:00'),
      location: 'Gare Saint-Charles',
      participants: ['William', 'Pierre', 'Youss'],
      details: ['Arrivée équipe technique', 'Transport vers chez Benny'],
    }),
    step({
      id: 'fri-depart-vitrolles',
      title: 'DÉPART VERS VITROLLES',
      phase: 'Trajet',
      start: at(D.fri, '17:00'),
      end: at(D.fri, '17:45'),
      location: 'Chez Benny → Vitrolles',
      details: ['Départ de chez Benny', 'Arrivée plateau ~18h00'],
    }),
    step({
      id: 'fri-setup',
      title: 'SETUP TECHNIQUE',
      phase: 'Setup',
      start: at(D.fri, '18:00'),
      end: at(D.fri, '19:45'),
      location: 'Plateau de Vitrolles',
      participants: ['Benny', 'William', 'Pierre', 'Youss'],
      equipment: ['FX6', 'Ronin RS3 Pro', 'Astera', 'Pavotube'],
      details: ['Installation lumière', 'Setup caméra & stabilisation'],
    }),
    step({
      id: 'fri-visuel1-a',
      title: 'SOUS DROP — VISUEL 1',
      phase: 'Tournage',
      start: at(D.fri, '19:45'),
      end: at(D.fri, '20:25'),
      location: 'Plateau de Vitrolles',
      participants: ['Tehazed', 'Mad', 'Eva'],
      equipment: ['FX6', 'Ronin', 'Astera'],
      details: ['Priorité haute', 'Plan 1', 'Plan 2', 'Plan 3'],
    }),
    step({
      id: 'fri-visuel1-b',
      title: 'SOUS DROP — VISUEL 1 (suite)',
      phase: 'Tournage',
      start: at(D.fri, '20:30'),
      end: at(D.fri, '21:45'),
      location: 'Plateau de Vitrolles',
      participants: ['Tehazed', 'Mad', 'Benny', 'William'],
      equipment: ['FX6', 'Ronin', 'DZO 50'],
      details: ['Plan 4A', 'Plan 4B', 'Plan 4C', 'Plan 5A', 'Plan 5B', 'Plan 5C', 'Plan 6'],
    }),
    step({
      id: 'fri-pause',
      title: 'PAUSE',
      phase: 'Pause',
      start: at(D.fri, '21:45'),
      end: at(D.fri, '22:15'),
      participants: ['Tout le monde'],
    }),
    step({
      id: 'fri-drone',
      title: 'DRONE',
      phase: 'Drone',
      start: at(D.fri, '22:15'),
      end: at(D.fri, '23:00'),
      location: 'Plateau de Vitrolles',
      participants: ['Benny', 'Pierre'],
      equipment: ['Air 2S', 'Cinewhoop'],
      details: ['Visuel 1 — Plan 11', 'Visuel 3 — Plans 4', 'Visuel 3 — Plans 5'],
    }),
    step({
      id: 'fri-visuel2',
      title: 'SOUS DROP — VISUEL 2 & 3',
      phase: 'Tournage',
      start: at(D.fri, '23:00'),
      end: at(D.sat, '01:00'),
      location: 'Plateau de Vitrolles',
      participants: ['Tehazed', 'Mad', 'Eva', 'Benny', 'William'],
      equipment: ['FX6', 'FX3', 'Ronin', 'Astera'],
      details: [
        'Visuel 2 — Plans 1 à 6',
        'Visuel 3 — Plans 1 à 5',
        '⚠️ Si retard : Visuel 3 saute en priorité',
      ],
    }),
  ],
}

const samedi: Day = {
  id: 'samedi',
  label: 'Samedi',
  date: D.sat,
  subtitle: 'Atelier Romain — SOUS MORPHINE · 18 Rue Jean Cristofol, 13003',
  steps: [
    step({
      id: 'sat-arrivee',
      title: 'ARRIVÉE & INSTALLATION',
      phase: 'Setup',
      start: at(D.sat, '08:00'),
      end: at(D.sat, '08:45'),
      location: '18 Rue Jean Cristofol',
      participants: ['Benny', 'William', 'Pierre', 'Laurent', 'Youss'],
      equipment: ['Baignoire', 'Aquarium', 'Astera', 'Godox', 'Machine fumée', 'Décors'],
      details: ['Installation décor & accessoires'],
    }),
    step({
      id: 'sat-maquillage',
      title: 'MAQUILLAGE',
      phase: 'Maquillage',
      start: at(D.sat, '08:00'),
      end: at(D.sat, '09:00'),
      participants: ['Tehazed', 'Mad'],
    }),
    step({
      id: 'sat-tests',
      title: 'TESTS CAMÉRA',
      phase: 'Tests',
      start: at(D.sat, '09:00'),
      end: at(D.sat, '09:30'),
      participants: ['Benny', 'William'],
      equipment: ['FX6', 'FX3', 'Lumière'],
    }),
    step({
      id: 'sat-morphine-v1',
      title: 'SOUS MORPHINE — VISUEL 1',
      phase: 'Tournage',
      start: at(D.sat, '09:30'),
      end: at(D.sat, '13:00'),
      location: 'Atelier Romain',
      participants: ['Tehazed', 'Mad', 'Benny', 'William'],
      equipment: ['FX6', 'DZO 25', 'DZO 50', 'Astera'],
      details: ['Plans 1A · 1B · 5A · 5B · 5C', 'Puis 2 · 3A · 3B · 4A · 4B'],
    }),
    step({
      id: 'sat-tenues-1',
      title: 'CHANGEMENT TENUES',
      phase: 'Pause',
      start: at(D.sat, '13:00'),
      end: at(D.sat, '13:15'),
      participants: ['Tehazed', 'Mad', 'Youss'],
    }),
    step({
      id: 'sat-katyperi-v3',
      title: 'KATY PERI — VISUEL 3',
      phase: 'Tournage',
      start: at(D.sat, '13:15'),
      end: at(D.sat, '14:00'),
      location: 'Atelier Romain',
      participants: ['Tehazed', 'Mad', 'Youss'],
      equipment: ['FX3', 'DZO 16'],
      details: ['Plan 1A', 'Plan 1B', 'Plan 2'],
    }),
    step({
      id: 'sat-repas',
      title: 'PAUSE REPAS',
      phase: 'Pause',
      start: at(D.sat, '14:00'),
      end: at(D.sat, '15:00'),
      participants: ['Tout le monde'],
      details: ['Recharge batteries', 'Sauvegarde rushs'],
    }),
    step({
      id: 'sat-retour-voiture',
      title: 'RETOUR VOITURE LOCATION',
      phase: 'Trajet',
      start: at(D.sat, '15:00'),
      end: at(D.sat, '15:30'),
      location: '22 Rue de Crimée',
      participants: ['Laurent'],
      details: ['Responsable : Laurent'],
    }),
    step({
      id: 'sat-morphine-v2',
      title: 'SOUS MORPHINE — VISUEL 2',
      phase: 'Tournage',
      start: at(D.sat, '15:00'),
      end: at(D.sat, '18:30'),
      location: 'Atelier Romain',
      participants: ['Tehazed', 'Mad', 'Benny', 'William'],
      equipment: ['Aquarium', 'FX6', 'Astera', 'Machine fumée'],
      details: ['Plans 1 à 6', 'Séquence aquarium'],
    }),
    step({
      id: 'sat-rangement',
      title: 'RANGEMENT + PAUSE',
      phase: 'Rangement',
      start: at(D.sat, '18:30'),
      end: at(D.sat, '19:30'),
      participants: ['Tout le monde'],
      details: ['Préparation soirée'],
    }),
    step({
      id: 'sat-soir-setup',
      title: 'KATY PERI — SETUP SOIRÉE',
      phase: 'Setup',
      start: at(D.sat, '20:30'),
      end: at(D.sat, '21:00'),
      location: 'Allée des 2 Pins · 76 Rue Chalusset',
      participants: ['Benny', 'William', 'Laurent'],
      equipment: ['Pavotube', 'Godox'],
      details: ['Installation lumière', 'Changement tenues'],
    }),
    step({
      id: 'sat-soir-v12-a',
      title: 'KATY PERI — VISUELS 1 & 2',
      phase: 'Tournage',
      start: at(D.sat, '21:00'),
      end: at(D.sat, '22:00'),
      location: 'Allée des 2 Pins',
      participants: ['Tehazed', 'Mad', 'Benny'],
      equipment: ['FX6', 'DZO 90'],
      details: ['Plan 1', 'Plan 2'],
    }),
    step({
      id: 'sat-soir-v12-b',
      title: 'KATY PERI — VISUELS 1 & 2 (nuit)',
      phase: 'Tournage',
      start: at(D.sat, '22:00'),
      end: at(D.sun, '00:00'),
      location: 'Pont / Autoroute',
      participants: ['Tehazed', 'Mad', 'Benny', 'William'],
      equipment: ['FX6', 'Sony 16-35'],
      details: ['Plans 13 · 14 · 15 · 16', 'Priorité : Pont · Autoroute · Longues expositions'],
    }),
  ],
}

const dimanche: Day = {
  id: 'dimanche',
  label: 'Dimanche',
  date: D.sun,
  subtitle: 'Calanque de Samena — READY TO SELL · Call 04h00',
  steps: [
    step({
      id: 'sun-setup',
      title: 'SETUP — CALANQUE',
      phase: 'Setup',
      start: at(D.sun, '04:00'),
      end: at(D.sun, '05:00'),
      location: 'Calanque de Samena',
      participants: ['Benny', 'William', 'Pierre', 'Laurent'],
      equipment: ['Drone', 'Baignoire', 'Pavotube', 'Godox'],
      details: ['Installation', 'Préparation drone', 'Lumière'],
    }),
    step({
      id: 'sun-stylisme',
      title: 'STYLISME',
      phase: 'Maquillage',
      start: at(D.sun, '04:00'),
      end: at(D.sun, '05:00'),
      participants: ['Mad', 'Tehazed'],
    }),
    step({
      id: 'sun-tournage-rts',
      title: 'READY TO SELL — TOURNAGE',
      phase: 'Tournage',
      start: at(D.sun, '05:15'),
      end: at(D.sun, '07:15'),
      location: 'Calanque de Samena',
      participants: ['Tehazed', 'Mad', 'Benny', 'William'],
      equipment: ['FX6', 'DZO 25', 'Astera'],
      details: ['Visuel 1 — Plans 1A · 1B · 1C', 'Visuel 2 — plans prévus'],
    }),
    step({
      id: 'sun-drone',
      title: 'DRONE — LEVER DE SOLEIL',
      phase: 'Drone',
      start: at(D.sun, '07:15'),
      end: at(D.sun, '08:00'),
      location: 'Calanque de Samena',
      participants: ['Benny', 'Pierre'],
      equipment: ['Air 2S', 'Mini 5 Pro'],
      details: ['Plans soleil levant', 'Beauty shots'],
    }),
    step({
      id: 'sun-pause',
      title: 'PAUSE GÉNÉRALE',
      phase: 'Pause',
      start: at(D.sun, '08:00'),
      end: at(D.sun, '17:00'),
      participants: ['Tout le monde'],
      details: ['Repos équipe', 'Déjeuner', 'Recharge batteries', 'Sauvegarde rushs', 'Dépôt baignoire chez Benny'],
    }),
    step({
      id: 'sun-corbusier',
      title: 'LE CORBUSIER — READY TO SELL V3',
      phase: 'Tournage',
      start: at(D.sun, '17:00'),
      end: at(D.sun, '19:30'),
      location: 'Le Corbusier',
      participants: ['Tehazed', 'Mad', 'Benny', 'William'],
      equipment: ['FX6', 'DZO 50'],
      details: ['Visuel 3 — Plan 1'],
    }),
    step({
      id: 'sun-joliette',
      title: 'LA JOLIETTE — KATY PERI',
      phase: 'Tournage',
      start: at(D.sun, '20:00'),
      end: at(D.sun, '22:00'),
      location: 'Rue Cavalier Paul',
      participants: ['Tehazed', 'Mad', 'Benny'],
      equipment: ['FX6', 'Sony 16-35'],
      details: ['Plans 13 · 14 · 15 · 16'],
    }),
  ],
}

const team: Person[] = [
  { id: 'p-tehazed', name: 'Tehazed', role: 'Artiste principal', availability: 'Dispo à partir de 17h', phone: '06 12 00 00 01' },
  { id: 'p-mad', name: 'Mad', role: 'Actrice principale', availability: 'Tout le week-end', phone: '06 12 00 00 02' },
  { id: 'p-eva', name: 'Eva', role: 'Second rôle', availability: 'Vendredi & Dimanche' },
  { id: 'p-lea', name: 'Lea', role: 'Second rôle', availability: 'Vendredi' },
  { id: 'p-laurent', name: 'Laurent', role: 'Régie / Coordination générale', availability: 'Tout le week-end', phone: '06 12 00 00 05', vehicle: 'Voiture régie' },
  { id: 'p-simon', name: 'Simon', role: 'Support régie', availability: 'Tout le week-end' },
  { id: 'p-benny', name: 'Benny', role: 'Chef opérateur', availability: 'Dès 15h vendredi', phone: '06 12 00 00 07', vehicle: 'Voiture location' },
  { id: 'p-william', name: 'William', role: 'Assistant caméra / Focus Puller', availability: 'Tout le week-end' },
  { id: 'p-pierre', name: 'Pierre', role: 'BTS / Assistant', availability: 'Tout le week-end' },
  { id: 'p-youss', name: 'Youss', role: 'BTS + Feat artiste', availability: 'Vendredi & Samedi' },
]

const vehicles: Vehicle[] = [
  {
    id: 'v-location',
    name: 'Voiture location',
    driver: 'Benny',
    passengers: ['Eva'],
    cargo: ['Lumières', 'Astera', 'Godox'],
  },
  {
    id: 'v-regie',
    name: 'Voiture régie',
    driver: 'Laurent',
    passengers: ['Simon', 'Mad'],
    cargo: ['FX6', 'FX3', 'Ronin', 'Régie / câblage'],
  },
  {
    id: 'v-bts',
    name: 'Voiture BTS',
    driver: 'William',
    passengers: ['Pierre', 'Youss'],
    cargo: ['Sony A7III x2', 'Drones', 'Batteries'],
  },
]

function cat(id: string, name: string, items: [string, boolean?][]): ChecklistCategory {
  return {
    id,
    name,
    items: items.map(([label, checked], i) => ({
      id: `${id}-${i}`,
      label,
      checked: Boolean(checked),
    })),
  }
}

const checklists: ChecklistCategory[] = [
  cat('cl-camera', 'Caméra', [
    ['FX6', true],
    ['FX3', true],
    ['Ronin RS3 PRO', true],
    ['Atomos Ninja V'],
    ['Tilta Nucleus'],
    ['DZO 16', true],
    ['DZO 25', true],
    ['DZO 50'],
    ['DZO 90'],
    ['DZO 125'],
    ['Sony 16-35', true],
    ['Black Mist 1/8'],
    ['Black Mist 1/4'],
    ['Batteries FX6', true],
    ['Batteries FX3'],
    ['Batteries Ronin'],
    ['Cartes SD', true],
    ['Cartes CFExpress'],
  ]),
  cat('cl-bts', 'BTS', [
    ['Sony A7III — Pierre', true],
    ['Sony A7III — Youss'],
    ['24-70'],
    ['Batteries'],
    ['Cartes mémoire'],
  ]),
  cat('cl-drone', 'Drone', [
    ['Air 2S', true],
    ['Mini 5 Pro'],
    ['Tinywhoop'],
    ['Cinewhoop 1'],
    ['Cinewhoop 2'],
    ['Racer 5"'],
    ['Batteries'],
    ['Hélices'],
    ['Chargeurs'],
  ]),
  cat('cl-lumiere', 'Lumière', [
    ['Pavotube x4', true],
    ['Godox x2', true],
    ['Skylite'],
    ['Diffusions'],
    ['Réflecteurs'],
    ['Poly noir/blanc'],
    ['Drapeaux'],
    ['Pieds', true],
    ['Rotules'],
  ]),
  cat('cl-regie', 'Régie', [
    ['Talkies-walkies'],
    ['Rallonges'],
    ['Multiprises'],
    ['Gaffer'],
    ['Trousse de secours'],
    ['Eau & snacks'],
  ]),
  cat('cl-accessoires', 'Accessoires', [
    ['Disques durs SSD'],
    ['Lecteur de cartes'],
    ['Chargeurs USB-C'],
    ['Powerbanks'],
    ['Trépieds photo'],
  ]),
]

export const mockRoadmap: Roadmap = {
  projectName: 'Capsules TEHAZED',
  subtitle: 'READY TO SELL · SOUS DROP · SOUS MORPHINE · KATY PERI',
  days: [vendredi, samedi, dimanche],
  team,
  vehicles,
  checklists,
  version: ROADMAP_VERSION,
}
